### ISSUE TITLE
alpha detecting 

### ISSUE THREAD

**Issue by Speuta** [evolution-gaming/babylonjs-texture-generator#1]
Hi,
Thanks for this great module !!
Can you please use something like [node-png-has-alpha](https://github.com/tj/node-png-has-alpha) module for detecting if .png files have alpha instead of just checking extension (ETC1 export) ?
Furthermore, how about a "DXT" export format ?
Many thanks !!

**Comment by hansagames** [comment]
Thank you for report

**Comment by hansagames** [comment]
Added support for DTX and alpha detection in version 1.0.2
